### ISSUE TITLE
Plugin content cannot be found from engine

### ISSUE THREAD

**Issue by ParkkiSakko** [IamKingWaiMark/GoogleAdmobBlueprint#2]
Hey, I tried using this plugin for ads, but my game keeps crashing at launch, no matter what settings I use. I followed the Youtube tutorial exatly, and yet I ran into this issue. When I try to open the create banner ad node (others give the same error) with Visual studio, I get an error could't find code file. What could be a solution for this whole issue?

- Metadata is set
- Default Admob is disabled
- I have tried to lauch the game without the codes firing, still crashes so the issue must be with the plugin itself
![image](https://user-images.githubusercontent.com/88910539/235918954-6e80e13c-cb0f-46d3-9cd6-b76f6803c3a8.png)

**Comment by IamKingWaiMark** [comment]
Hello,

Can't really see the full path from those messages. 

But:

1) Make a copy of your project
2) Delete the Intermediate, Binaries, and Saved folders
3) Launch the Unreal Engine project
4) Wait for it to finish building (You may not see it building and need to wait some time)


Also, if you navigate to that path that it is saying, what do you see?

**Comment by ParkkiSakko** [comment]
I tried these, none of them worked. Also I can't find such a directory from my PC. I have no idea what could be an issue. If I disable the plugin the game works fine, but as soon as I enable it, game starts crashing. Doesn't matter are the codes firing or not. What else could I try? Engine is UE 5.0.3

**Comment by IamKingWaiMark** [comment]
Not sure, hard to tell since it seems like it is some settings related to where the project is looking for the plugin on your system.

Did you install the plugin from the launcher?

It should be located in the in the UE_VERSION/Engine/Plugins/Marketplace directory.

Maybe uninstall the plugin from the launcher, launch the app. Then reinstall the plugin and try again.

**Comment by IamKingWaiMark** [comment]
Also, do you have the logs in the Output window?

**Comment by IamKingWaiMark** [comment]
Also can you show a screenshot of what you are doing?

**Comment by ParkkiSakko** [comment]
Here are a few screenshots. I found the directory and uninstalled the plugin and reinstalled it. Here's an image from my game instance and from the level calling the event located in the game instance. 
![image](https://user-images.githubusercontent.com/88910539/235942164-519c48d8-1cb9-4ec9-abc7-c3422ed72db5.png)

![image](https://user-images.githubusercontent.com/88910539/235942279-15edf7a2-d18b-4415-95b1-ac127ae2b435.png)


Here are my packaging settings:
![image](https://user-images.githubusercontent.com/88910539/235942783-0596820d-6953-41ed-84c4-58c41a7c3cec.png)

And here are my Android settings:
![image](https://user-images.githubusercontent.com/88910539/235942927-382248cf-5d89-4670-97ae-6d9d3825d85a.png)

![image](https://user-images.githubusercontent.com/88910539/235943117-0b515507-f07d-4719-b10c-8059916088ea.png)

![image](https://user-images.githubusercontent.com/88910539/235943211-9fb4607a-2803-40ea-aeec-a4638de22e7a.png)

![image](https://user-images.githubusercontent.com/88910539/235943312-85929e79-3323-42fe-8ee7-bc51a857b40f.png)

![image](https://user-images.githubusercontent.com/88910539/235943394-b0e11322-78ac-46a9-9102-2e82770ad8eb.png)

The game is Android only, so iOS is not set up. 

Also here's the output log when I try to quick launch the game on my phone. It gives success, but it'll crash once launched:
[TheWallOfMoney.log](https://github.com/IamKingWaiMark/GoogleAdmobBlueprint/files/11383471/TheWallOfMoney.log)

**Comment by IamKingWaiMark** [comment]
Hi, 

After looking at the screenshots, it should be fine with the setup for the plugin. Logs looks normal.

However, it may be how you setup your nodes in the game instance and calling it. Unreal tends to crash if stuff are not executed in the same thread. Since all the nodes in the plugins are non-blocking code that waits for events, it is best to call them in the same place.

Once GMA is initialize you should be able to call the nodes anywhere like normal.

To test, you can try to:

1) Change the package name to : com.ue.admob.blueprint.plugin (although your package should work unless you have admob setup but it is imcomplete)
2) Init Google Mobile ads like this in the game instance:

**Comment by IamKingWaiMark** [comment]
![image](https://user-images.githubusercontent.com/42749516/236094300-3013473a-ba31-4665-9f37-def27fc8bf85.png)

**Comment by IamKingWaiMark** [comment]
See if your app launches.

Then do this to test the banner ad:

**Comment by IamKingWaiMark** [comment]
![image](https://user-images.githubusercontent.com/42749516/236094570-00340878-3519-44b4-be47-a5c421ebc6c0.png)

**Comment by IamKingWaiMark** [comment]
Also try this example project:

https://drive.google.com/file/d/14UBqLYmteb2Gx4UOQnS2LrLF9UViHG9E/view?usp=sharing

**Comment by ParkkiSakko** [comment]
Tried this out, didn't work. I can't set the package name as com.ue.admob.blueprint.plugin, it fails in the packaging phase. The app is already published on Google Play, so the settings would get mixed. 

Looks like the app will crash once it tries to init the GMA. But if I launch my game with the plugin completely disabled, it works fine. I'm worried that the issue mentioned first in this thread causes the issue. 

The content folder of this plugin is empty. Is that supposed to be?

**Comment by ParkkiSakko** [comment]
![image](https://user-images.githubusercontent.com/88910539/236203549-ec425bf9-31b8-4f86-9448-6c5547495990.png)

**Comment by IamKingWaiMark** [comment]
Yes, nothing should be in the contents folder

**Comment by IamKingWaiMark** [comment]
Are you able to test with a new project and launch? 

This can help confirm if there is some settings/preferences on your system that can effect it.

**Comment by ParkkiSakko** [comment]
I tried with a new test project. Worked! Init was succesfull and the blank game started after around 5 seconds of waiting. So something is wrong with the files in my actual project. 

I used the same settings than in the photos above and named the package com.ue.admob.blueprint.plugin. Could the problem be inside the google play services json file or somewhere else?

**Comment by ParkkiSakko** [comment]
Do you know is there a way to set UE not use C++ sources? I once had an actor in C++, but I no longer have it, so the source folder is still there and the project now requires it to be able to launch. Could that be one of the issues?

**Comment by ParkkiSakko** [comment]
When I build development version, it launches perfectly even in the actual project, but shipping and distribution version crashes at launch. So shipping is the issue, not the project

**Comment by ParkkiSakko** [comment]
I have now come to a conclusion that the issue is caused by "for distribution" checkmark. If I disable it, game works with ads, but Google Play doesn't allow that file to be sent to the store. Also the package size is now over 200MB instead of previous 85MB. 

If it's enabled, the game crashes at launch, but the size is back to normal 85MB. So how I could bypass that issue but still be able to upload the game to the store?

**Comment by IamKingWaiMark** [comment]
Hello thanks for the updates, is your packaged app a aab file?

**Comment by ParkkiSakko** [comment]
Yes, because Google requires it to be AAB file. APK's cannot be uploaded to Google anymore

**Comment by ParkkiSakko** [comment]
I have sent the newest version to Google Play and I'll see if it works normal when lauched from the store. If that doesn't work then we have to solve that issue with distribution setting.

**Comment by ParkkiSakko** [comment]
Google Play rejected the app this morning due stability. For distribution button is the issue at this time. Any idea what I could do to get it to Google?

![image](https://user-images.githubusercontent.com/88910539/236429914-e563ac13-7535-43e6-8293-68fcb32fa237.png)

**Comment by emrebarisc** [comment]
I have the same issue. There are no errors on builds which are not for distribution, but game crashes with 'For Distribution' option selected.

**Comment by IamKingWaiMark** [comment]
Hi, sure.

Looking into this and trying to reproduce the issue on my end to see.

So far cannot reproduce but will see other ways.

**Comment by ParkkiSakko** [comment]
Hi, just to make sure, are there any other plugins that this admob system requires for this to work? Or is just this required?

**Comment by IamKingWaiMark** [comment]
Hi, no other plugins are needed.

**Comment by emrebarisc** [comment]
Hello. Do you have any updates?

**Comment by emrebarisc** [comment]
Hello again. Don't you have any updates about the crash yet? Please keep giving information about the process in a transparent way. If not, I will contact Epic Games with my complaints and refund request.

**Comment by emrebarisc** [comment]
Hello again.

Do you have any updates about the crash yet? Please continue to provide information about the process transparently.

If not, I have to contact Epic Games with my complaints and refund request.

**Comment by IamKingWaiMark** [comment]
Hi, for now, please request for a refund.

**Comment by juvilianvfx** [comment]
@IamKingWaiMark  Exact same issue. Initializing in game instance or level blueprint, both crashes the game. If you want i can send you the entire project, may help you to fix this issue for ever. 

i am using 5.1.1 

please let me know if you have any solution for this ?

**Comment by IamKingWaiMark** [comment]
@juvilianvfx Make sure:

1) Include AdMob support for ads is disabled in Android > Google Player Services
![image](https://github.com/IamKingWaiMark/GoogleAdmobBlueprint/assets/42749516/141e1c7e-a629-41e8-a26d-156b853206cc)

2) The meta-data element is there without spaces in the beginning
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713"/>

3) The package name matches the one in the google-services.json or plist file

4) Game development with C++ is installed on Visual Studio and Android IDE support for Unreal is installed
![image](https://github.com/IamKingWaiMark/GoogleAdmobBlueprint/assets/42749516/5f7fe6ef-e96c-432a-bad6-d7c6cd60e25a)

5) You are using this version for the ndk - 25.1.8937393
